title: BeeWatch
description: Beeminder for Apple Watch - Track your goals from your wrist
url: "https://giovannicoppola.github.io"
baseurl: "/beeWatch"
theme: null

# GitHub Pages settings
plugins:
  - jekyll-seo-tag
